#!/bin/sh
# Setup needed in order too link files to correct position
FILES=".bashrc .aliases " 
echo Making softlinks
#Change to homedir
cd ~ 

DIR=".config/fish"
if [ -d "$DIR" ]; then
  # Take action if $DIR exists. #
  echo "Fish config dir exists. Using it too"
  FILES="${FILES} .config/fish/config.fish"
fi



for FILE in $FILES
do
   if [ -f "$FILE" ]; then
   echo "$FILE already exists. Moving to $FILE.bak"
   mv $FILE $FILE.bak
   fi
   ln -s .dotfiles/$FILE $FILE

done

