#!/bin/sh
# Setup needed in order too link files to correct position
FILES=".bashrc .aliases .config/fish/config.fish" 

#Change to homedir
cd ~ 

for FILE in FILES
do
   if [ -f "$FILE" ]; then
   echo "$FILE already exists. Moving to $FILE.bak"
   mv $FILE $FILE.bak
   fi
   ln -s .dotfiles/$FILE $FILE

done

